name: Bug Report
description: Report a bug or issue with Markdown for Humans
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us reproduce and fix the issue.
        
        **Before reporting:** Check [KNOWN_ISSUES.md](https://github.com/concretios/markdown-for-humans/blob/main/KNOWN_ISSUES.md) to see if this is already a known issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open a .md file
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screen-recording
    attributes:
      label: Screen Recording (Required)
      description: |
        **Please provide a screen recording** using [Loom.com](https://www.loom.com) or similar tool showing the issue.
        This makes it much easier to visualize and reproduce the problem.
        
        Steps:
        1. Record your screen showing the bug
        2. Upload to Loom.com (or similar: ScreenPal, CloudApp, etc.)
        3. Paste the shareable link here
      placeholder: https://www.loom.com/share/...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (Optional)
      description: If applicable, add screenshots to supplement the screen recording
      placeholder: Drag and drop images here...

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of Markdown for Humans are you using? (Check in Extensions view or package.json)
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: What version of VS Code are you using? (Help → About or code --version)
      placeholder: e.g., 1.85.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version (if known)
      description: Node.js version if you're building from source (optional)
      placeholder: e.g., 20.10.0

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    id: file-scheme
    attributes:
      label: File Scheme
      description: Is the file a saved file or untitled?
      options:
        - file: (saved file)
        - untitled: (unsaved/new file)
        - Not applicable
    validations:
      required: false

  - type: checkboxes
    id: workspace
    attributes:
      label: Workspace
      description: Workspace context
      options:
        - label: Workspace folder is open
          required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please include relevant logs. You can find them in:
        - Extension logs: View → Output → "Markdown for Humans"
        - Webview logs: Developer → Open Webview Developer Tools → Console (look for [MD4H] messages)
      placeholder: |
        [Extension Output]
        ...
        
        [Webview Console]
        ...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., related to images, tables, mermaid diagrams, etc.)
      placeholder: |
        - Does this involve images? (local/workspace/external URL)
        - Does this involve tables, mermaid diagrams, or other features?
        - Any error messages in the console?
        - Does this happen with specific markdown content?

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
