name: Question
description: Ask a question about using or contributing to Markdown for Humans
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! For general questions, consider using [GitHub Discussions](https://github.com/concretios/markdown-for-humans/discussions) instead. Use this template for questions that might need follow-up or are related to bugs/features.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your question
      placeholder: |
        - What are you trying to accomplish?
        - What have you tried so far?
        - Any relevant code examples or screenshots?
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Usage/How to use a feature
        - Installation/Setup
        - Configuration
        - Contributing/Development
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this question, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

